version: '3.8'

services:
  odoo:
    image: odoo:18
    hostname: odoo
    depends_on:
      - postgres
    ports:
      - "${ODOO_PORT:-8069}:8069"
    volumes:
      - odoo-filestore:/var/lib/odoo/filestore
      - odoo-addons:/mnt/extra-addons
      - odoo-config:/etc/odoo
    env_file:
      - .env
    environment:
      - HOST=postgres
      - USER_FILE=/run/secrets/postgres_user
      - PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
      - odoo_admin_password
    configs:
      - source: odoo_conf
        target: /etc/odoo/odoo.conf
    networks:
      - odoo_network
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker

  postgres:
    image: postgres:15
    hostname: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=postgres
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - odoo_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker

  pgadmin:
    image: dpage/pgadmin4:latest
    hostname: pgadmin
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL_FILE=/run/secrets/pgadmin_email
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
      - PGADMIN_LISTEN_PORT=80
    secrets:
      - pgadmin_email
      - pgadmin_password
    networks:
      - odoo_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker

volumes:
  odoo-filestore:
    driver: local
  odoo-addons:
    driver: local
  odoo-config:
    driver: local
  postgres-data:
    driver: local

networks:
  odoo_network:
    driver: overlay

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  pgadmin_email:
    external: true
  pgadmin_password:
    external: true
  odoo_admin_password:
    external: true

configs:
  odoo_conf:
    external: true
